### ISSUE TITLE
Action overwrites `GITHUB_PATH`, making other installed tools unaccessible

### ISSUE THREAD

**Issue by devpikachu** [houseabsolute/actions-rust-cross#1] opened 2023-03-07 14:57 UTC
Trying to use this action in my pipeline, and currently, the action overwrites `GITHUB_PATH`, thus making other installed tools unusable, such as `protoc` in my case.

```
 thread 'main' panicked at 'Could not find `protoc` installation and this build crate cannot proceed without
      this knowledge. If `protoc` is installed and this crate had trouble finding
      it, you can set the `PROTOC` environment variable with the specific path to your
      installed `protoc` binary.If you're on debian, try `apt-get install protobuf-compiler` or download it from https://github.com/protocolbuffers/protobuf/releases
```

https://github.com/houseabsolute/actions-rust-cross/blob/9a602122c2f4df61140216897231df93c0922a22/action.yml#LL29C12-L29C60

**Comment by autarch** [comment] 2023-03-12 14:21
Ah, I just saw this issue. This should be a simple fix.

**Comment by autarch** [comment] 2023-03-12 14:32
Actually, I'm a bit confused as to how this is happening. From reading [the GH Actions docs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-system-path) it seems like appending to `$GITHUB_PATH` should just add a directory, not wipe out any that already exist. Can you point me to workflow you're using that's having this issue?

**Comment by devpikachu** [comment] 2023-03-12 14:51
Hey @autarch ! Thanks for replying. Of course, see below:

- Latest run: https://github.com/omnilium/pandorica/actions/runs/4397996712/jobs/7701515589
- Workflow file: https://github.com/omnilium/pandorica/blob/main/.github/workflows/build.yml

**Comment by autarch** [comment] 2023-03-12 21:20
I wrote some tests to check for this. AFAICT it's _not_ overwriting the `$PATH`. See https://github.com/houseabsolute/actions-rust-cross/actions/runs/4399492494/jobs/7704067598#step:7:10

**Comment by autarch** [comment] 2023-03-12 21:27
Oh wait, I see what's happening. The problem is that builds for non-native architectures are run inside a Docker container. That container doesn't have protoc in it.

There's a number of ways to solve this but I think the simplest is to add pre-build hooks for cross that install protoc -https://github.com/cross-rs/cross#pre-build-hook

You might find [my `ubi` project](https://github.com/houseabsolute/ubi) handy for this.

**Comment by autarch** [comment] 2023-03-12 21:28
I'm going to close this since it's not a bug with the action. But on the plus side, it got me to write some tests for it, which is great!

**Closed by autarch** 2023-03-12 21:28 UTC

**Comment by autarch** [comment] 2023-03-12 22:25
I just realized `ubi` won't work with the protobuf project, since it ships more than just a binary in its releases.

**Comment by devpikachu** [comment] 2023-03-13 08:48
@autarch Thank you so much for looking into this and for providing this very valuable insight. It makes perfect sense why it doesn't work and it totally slipped my mind checking for the fact that it runs inside a docker container.

I will go about adding pre-build hooks as linked above.
